# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{using_yaml}
  s.version = "0.3.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Marc Bowes"]
  s.date = %q{2010-02-15}
  s.description = %q{"Load, save and use YAML files as if they were objects"}
  s.email = %q{marcbowes@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "lib/using_yaml.rb",
     "lib/using_yaml/open_hash.rb",
     "lib/using_yaml/patches/hash.rb",
     "spec/spec_helper.rb",
     "spec/using_yaml/path_spec.rb",
     "spec/using_yaml/using_yaml_spec.rb",
     "using_yaml.gemspec"
  ]
  s.homepage = %q{http://github.com/marcbowes/UsingYAML}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{"Load, save and use YAML files"}
  s.test_files = [
    "spec/using_yaml/path_spec.rb",
     "spec/using_yaml/using_yaml_spec.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<thoughtbot-shoulda>, [">= 0"])
    else
      s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
    end
  else
    s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
  end
end

